Fix CORS allowed_hosts example in README
The example config yaml cause error message:
```
Error: While parsing config: yaml: line 67: did not find expected alphabetic or numeric character
```